# Generated by Django 4.2.6 on 2023-10-30 01:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articulos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo_sku",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("descripcion", models.CharField(max_length=150)),
                ("factor_compra", models.IntegerField()),
                ("factor_reparto", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nro_documento", models.CharField(max_length=11)),
                ("razon_social", models.CharField(max_length=150)),
                ("direccion", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="GruposProveedor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo_grupo",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("grupo_descripcion", models.CharField(max_length=100)),
                ("activo", models.BooleanField()),
                ("responsable_grupo", models.CharField(max_length=25)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventarios",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha_inventario", models.DateTimeField()),
                ("nro_inventario", models.IntegerField()),
                ("hora_inicio", models.DateTimeField()),
                ("hora_fin", models.DateTimeField()),
                (
                    "total_inventario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("IP", "In Progress"),
                            ("C", "Closed"),
                        ],
                        default="P",
                        max_length=2,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="LineasArticulos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo_linea",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("linea_descripcion", models.CharField(max_length=100)),
                ("activo", models.BooleanField()),
                ("responsable_linea", models.CharField(max_length=25)),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.gruposproveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marcas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo_marca",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("marca_nombre", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="UnidadesMedida",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("unidad_nombre", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=25)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursales",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre_comercial", models.CharField(max_length=150)),
                ("direccion", models.CharField(max_length=150)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SublineasArticulos",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "codigo_sublinea",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("sublinea_descripcion", models.CharField(max_length=100)),
                ("estado", models.BooleanField()),
                (
                    "linea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.lineasarticulos",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Personal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre_personal", models.CharField(max_length=100)),
                ("direccion_personal", models.CharField(max_length=150)),
                ("tipo_documento", models.CharField(max_length=1)),
                ("nro_documento", models.CharField(max_length=11)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.empresa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemsInventario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nro_item", models.IntegerField()),
                ("stock_fisico", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "devoluciones_pendientes",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "total_unidades_stock",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("precio_costo", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_item", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.articulos",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.inventarios",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inventarios",
            name="cerrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventarios_cerrados",
                to="common.usuarios",
            ),
        ),
        migrations.AddField(
            model_name="inventarios",
            name="creado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventarios_registrados",
                to="common.usuarios",
            ),
        ),
        migrations.AddField(
            model_name="inventarios",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.empresa"
            ),
        ),
        migrations.AddField(
            model_name="inventarios",
            name="responsable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.personal"
            ),
        ),
        migrations.AddField(
            model_name="inventarios",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.sucursales"
            ),
        ),
        migrations.AddField(
            model_name="articulos",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.empresa"
            ),
        ),
        migrations.AddField(
            model_name="articulos",
            name="grupo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.gruposproveedor"
            ),
        ),
        migrations.AddField(
            model_name="articulos",
            name="linea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.lineasarticulos"
            ),
        ),
        migrations.AddField(
            model_name="articulos",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.marcas"
            ),
        ),
        migrations.AddField(
            model_name="articulos",
            name="sublinea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="common.sublineasarticulos",
            ),
        ),
        migrations.AddField(
            model_name="articulos",
            name="unidad_medida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.unidadesmedida"
            ),
        ),
    ]
