# Generated by Django 4.2.6 on 2023-10-30 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_alter_unidadesmedida_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personal",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("DNI", "documento de identidad"),
                    ("CNT", "Carnet de extranjeria"),
                ],
                default="DNI",
                max_length=3,
            ),
        ),
    ]
